default_expiration: "1d"
handlers:
- url: '/'
  static_files: 'stanice.html'
  upload: '.*'
- url: '/stanice'
  static_files: 'stanice.html'
  upload: '.*'
- url: '/kontakt'
  static_files: 'kontakt.html'
  upload: '.*'
- url: '/'
  static_dir: '/'